[package]
name = "calc_num"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
lstsq = "0.7.0"
nalgebra = "0.34.1"
plotters = "0.3.7"
rand = "0.9.2"
rust_decimal = {version = "1.38.0", features = ["macros"]}
serde = {version = "1.0.228", features = ["serde_derive"]}